# Generated by Django 5.1 on 2024-08-17 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.facultades')),
            ],
        ),
        migrations.CreateModel(
            name='CodigosHora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_hora', models.CharField(max_length=50)),
                ('dia_semana', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=100)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.carreras')),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.facultades')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.materias')),
            ],
        ),
        migrations.CreateModel(
            name='MateriasCarreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.carreras')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.materias')),
            ],
            options={
                'unique_together': {('id_materia', 'id_carrera')},
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.codigoshora')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.estudiantes')),
            ],
            options={
                'unique_together': {('id_estudiante', 'id_codigo')},
            },
        ),
    ]
