# Generated by Django 5.1 on 2024-08-18 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hora', models.CharField(max_length=10)),
                ('dia_semana', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=100)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.carreras')),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.facultades')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.materias')),
            ],
        ),
    ]
