# Generated by Django 5.1 on 2024-09-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_horario', '0002_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
