# Generated by Django 5.1 on 2024-09-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagen_preP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_base64', models.TextField()),
            ],
            options={
                'db_table': 'imagen_preP',
            },
        ),
    ]
