# Generated by Django 5.1 on 2024-09-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_imagen_prep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagen_preP',
        ),
    ]
