# Generated by Django 5.1 on 2024-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_delete_imagen_prep'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'app_usuarios_user_groups',
                'managed': False,
            },
        ),
    ]
