# Generated by Django 5.1 on 2024-11-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0006_outstandingtoken'),
    ]

    operations = [
    ]
