# Generated by Django 5.1 on 2024-09-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_horario', '0003_delete_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField()),
                ('hora_asistencia', models.TimeField()),
                ('asistio', models.BooleanField()),
                ('codigo_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.codigoshora')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_horario.estudiantes')),
            ],
        ),
    ]
